"""Initial migration

Revision ID: 0448717c06f9
Revises: 
Create Date: 2025-09-23 14:48:05.283050

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0448717c06f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('thumb_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_column('thumb_path')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    # ### end Alembic commands ###
