"""empty message

Revision ID: 759513d7b885
Revises: 891b4c0f6468
Create Date: 2025-09-23 19:29:54.625349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '759513d7b885'
down_revision = '891b4c0f6468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    # ### end Alembic commands ###
