"""Add uid

Revision ID: 78a99fddf6e7
Revises: 969606519b6b
Create Date: 2025-10-05 16:31:54.499558

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78a99fddf6e7'
down_revision = '969606519b6b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - adjusted for SQLite ###
    # 旧表在部分环境并不存在，这里使用 IF EXISTS 以避免报错
    op.execute('DROP TABLE IF EXISTS rss_item')
    op.execute('DROP TABLE IF EXISTS rss_feed')
    op.execute('DROP TABLE IF EXISTS sms_reminder')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_event_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_type'), ['type'], unique=False)
        batch_op.create_index(batch_op.f('ix_event_user_id'), ['user_id'], unique=False)
        # SQLite 的 batch 模式要求外键约束提供名称
        batch_op.create_foreign_key('fk_event_user_id', 'user', ['user_id'], ['id'])

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_index('idx_moment_content', ['content'], unique=False)
        batch_op.create_index('idx_moment_timestamp_favorite', ['timestamp', 'is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_moment_is_favorite'), ['is_favorite'], unique=False)
        batch_op.create_index(batch_op.f('ix_moment_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_moment_user_id'), ['user_id'], unique=False)
        batch_op.create_foreign_key('fk_moment_user_id', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_constraint('fk_moment_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_moment_user_id'))
        batch_op.drop_index(batch_op.f('ix_moment_timestamp'))
        batch_op.drop_index(batch_op.f('ix_moment_is_favorite'))
        batch_op.drop_index('idx_moment_timestamp_favorite')
        batch_op.drop_index('idx_moment_content')
        batch_op.drop_column('user_id')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_constraint('fk_event_user_id', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_event_user_id'))
        batch_op.drop_index(batch_op.f('ix_event_type'))
        batch_op.drop_index(batch_op.f('ix_event_timestamp'))
        batch_op.drop_column('user_id')

    op.create_table('sms_reminder',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('phone_number', sa.VARCHAR(length=20), nullable=False),
    sa.Column('feed_reminder_enabled', sa.BOOLEAN(), nullable=True),
    sa.Column('feed_reminder_hours', sa.INTEGER(), nullable=True),
    sa.Column('last_reminder_sent', sa.DATETIME(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_feed',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), nullable=False),
    sa.Column('url', sa.VARCHAR(length=500), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('icon_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('last_updated', sa.DATETIME(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rss_item',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('feed_id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=300), nullable=False),
    sa.Column('description', sa.TEXT(), nullable=True),
    sa.Column('content', sa.TEXT(), nullable=True),
    sa.Column('link', sa.VARCHAR(length=500), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('pub_date', sa.DATETIME(), nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), nullable=True),
    sa.Column('is_favorite', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['rss_feed.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
