"""empty message

Revision ID: 891b4c0f6468
Revises: 0448717c06f9
Create Date: 2025-09-23 17:09:50.432610

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '891b4c0f6468'
down_revision = '0448717c06f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('video_path', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_column('video_path')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    # ### end Alembic commands ###
