"""Add RSSItem feed relationship

Revision ID: 969606519b6b
Revises: f06bfba6f470
Create Date: 2025-09-24 12:03:58.953331

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '969606519b6b'
down_revision = 'f06bfba6f470'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    # ### end Alembic commands ###
