"""empty message

Revision ID: a2303348397f
Revises: 759513d7b885
Create Date: 2025-09-23 20:53:25.360210

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2303348397f'
down_revision = '759513d7b885'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_favorite', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('moment', schema=None) as batch_op:
        batch_op.drop_column('is_favorite')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    # ### end Alembic commands ###
