"""Add RSS feed and item models

Revision ID: f06bfba6f470
Revises: a2303348397f
Create Date: 2025-09-24 11:43:28.898174

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f06bfba6f470'
down_revision = 'a2303348397f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('push_content')
    op.drop_table('user_preference')
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('idx_event_type_timestamp'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('idx_event_type_timestamp'), ['type', 'timestamp'], unique=False)

    op.create_table('user_preference',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('preference_key', sa.VARCHAR(length=50), nullable=False),
    sa.Column('preference_value', sa.TEXT(), nullable=False),
    sa.Column('updated_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('push_content',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('title', sa.VARCHAR(length=200), nullable=False),
    sa.Column('content', sa.TEXT(), nullable=False),
    sa.Column('content_type', sa.VARCHAR(length=20), nullable=False),
    sa.Column('category', sa.VARCHAR(length=50), nullable=False),
    sa.Column('image_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('video_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('external_url', sa.VARCHAR(length=500), nullable=True),
    sa.Column('age_range', sa.VARCHAR(length=20), nullable=True),
    sa.Column('priority', sa.INTEGER(), nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
